"""empty message

Revision ID: cbfedc9ad463
Revises: f006375819c7
Create Date: 2021-02-23 19:26:56.992347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbfedc9ad463'
down_revision = 'f006375819c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sharing_location', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sharing_location')
    # ### end Alembic commands ###
