"""empty message

Revision ID: d314381ed022
Revises: cbfedc9ad463
Create Date: 2021-02-23 19:44:21.698267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd314381ed022'
down_revision = 'cbfedc9ad463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('latitude', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    # ### end Alembic commands ###
